# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc7d8fd2effc8ecfe409652c92767e5cccdcc9ccdab443e25e44ce904b1d8f0d25176dbf07a2e6346671f137f937d18ec2c26729f0620e8f023dafc5fe6c9ff9

test:
  secret_key_base: e47d0581e1e285cc57aa3a793a4c371f57cd423ea7aa6b329b7159b20e99310ba469abe999a02ca44c96d14149bbbadd0270165703af78b7f3d7ecdfbd3d2b3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
